sudo: required
services:
  - docker

before_install:
  - docker build -t averaj2015/docker-react-f Dockerfile.dev .

script:
  - docker run averaj2015/docker-react npm run test -- --coverage

language: generic 